language: python
python:
  - 3.8
install:
  - pip install -q pipenv codecov
  - pipenv sync --dev
script:
  - flake8
  - pytest libpythonpro --cov=libpythonpro

# Enviar relatóro codecov após o build no travis-CI
after_success:
  - codecov